### ISSUE TITLE
Blank calendar after `org-hyperscheduler-open`

### ISSUE THREAD

**Issue by maikol-solis** [dmitrym0/org-hyperscheduler#4] opened 2022-05-03 19:49 UTC
First, thanks for the project. It looks very useful. 

However, after install and execute `M-x org-hyperscheduler-open` a new browser opens, but there is only a blank calendar and this wheel spinning forever. 

![image](https://user-images.githubusercontent.com/4078489/166553345-94ac0da1-4bbf-4896-b038-0ab3441ab419.png)
How could I debug this? 

Thanks for the help.

**Comment by dmitrym0** [comment] 2022-05-04 04:59
Hi @maikol-solis, sorry about that. Let's see if we can trouble shoot this..

The spinner is set to disappear once the first agenda list is generated, so it looks like for whatever reason your agenda isn't being properly generated.

I'm looking at the code, and looks like I've left `async-start` there, which doesn't work anyway. It's likely failing because of that. Can you try `M-S-: (org-hs--get-agenda)`. If this works for you, then it's likely the `async-start` like I'm thinking.

**Comment by maikol-solis** [comment] 2022-05-04 14:24
Thanks for the reply!

> Can you try `M-S-: (org-hs--get-agenda)`.

I did this and nothing happened. I appreciate if you could guide me to debug this further. 

Thanks.

**Comment by ifinkelstein** [comment] 2022-05-04 15:43
Thanks for your quick feedback. I tried `M-x org-hyperscheduler-open` but got the same blank calendar and spinning wheel.

Running 'M-S-: (org-hs--get-agenda)' produces the following debug trace:

'Debugger entered--Lisp error: (websocket-closed #s(websocket-frame :opcode text :payload "[{\"isReadOnly\":true,\"allDay\":\"true\",\"endDate\":\"202..." :length nil :completep t))
  websocket-send(#s(websocket :ready-state open :client-data nil :on-open org-hs--ws-on-open :on-message org-hs--ws-on-message :on-close #f(compiled-function (ws) #<bytecode -0x15db668e1913e9ec>) :on-error websocket-default-error-handler :negotiated-protocols nil :negotiated-extensions nil :server-p t :url #<process websocket server on port 44445 <127.0.0.1:62966>> :protocols nil :extensions nil :conn #<process websocket server on port 44445 <127.0.0.1:62966>> :server-conn #<process websocket server on port 44445> :accept-string "oT3wGhTD6ehGohzsT8b9l8FkMXg=" :inflight-input "\202\13rG\20\10\233") #s(websocket-frame :opcode text :payload "[{\"isReadOnly\":true,\"allDay\":\"true\",\"endDate\":\"202..." :length nil :completep t))
  websocket-send-text(#s(websocket :ready-state open :client-data nil :on-open org-hs--ws-on-open :on-message org-hs--ws-on-message :on-close #f(compiled-function (ws) #<bytecode -0x15db668e1913e9ec>) :on-error websocket-default-error-handler :negotiated-protocols nil :negotiated-extensions nil :server-p t :url #<process websocket server on port 44445 <127.0.0.1:62966>> :protocols nil :extensions nil :conn #<process websocket server on port 44445 <127.0.0.1:62966>> :server-conn #<process websocket server on port 44445> :accept-string "oT3wGhTD6ehGohzsT8b9l8FkMXg=" :inflight-input "\202\13rG\20\10\233") "[{\"isReadOnly\":true,\"allDay\":\"true\",\"endDate\":\"202...")
  org-hs--get-agenda()
  eval-expression((org-hs--get-agenda) nil nil 127)
  funcall-interactively(eval-expression (org-hs--get-agenda) nil nil 127)
  command-execute(eval-expression)'

**Comment by dmitrym0** [comment] 2022-05-04 16:02
@ifinkelstein I'll take a closer look.

org-hyperscheduler has no dependencies on org-roam. It uses org-mode functionality to generate a list of calendar entries. 

Thanks for helping trouble shoot this, I'm sure we'll get to the bottom of this.

**Comment by dmitrym0** [comment] 2022-05-05 15:43
Hi folks,

So far, I'm not able to reproduce this 🤷 

I tried a clean room install of Doom Emacs and it worked fine. 

I also tried Brave (a chrome variant), Safari and Firefox. All appear to work fine.

Can you share your version of OS, Emacs & the browser you're using?

Based on the stack trace, there seems to be an web socket error, but I don't understand the source or the cause of the error.

My next step is to instrument this, to add more debugging info. Perhaps your agenda payload is too large?

**Comment by maikol-solis** [comment] 2022-05-05 21:21
> Can you share your version of OS, Emacs & the browser you're using?

Sure!

Doom-emacs
```
generated    May 05, 2022 15:18:38
system       MacOS 11.6.5 Darwin 20.6.0 x86_64 ns
emacs        28.1 HEAD c2fb07fdb ~/.emacs.d/ -> ~/.emacs.d/
doom         3.0.0-dev HEAD -> master 80cd7557e 2022-05-05 20:32:54 +0200 ~/.doom.d/ -> ~/dotfiles/.doom.d/
shell        /bin/zsh
features     ACL DBUS GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS ZLIB
traits       gui server-running envvar-file custom-file
custom       x-underline-at-descent-line widget-image-enable
modules      :completion (company +tng) (vertico +icons) :ui deft doom (&nopath fill-column) hl-todo hydra minimap modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) (undo +tree) vc :checkers syntax (spell +flyspell +everywhere) grammar :tools biblio ein (eval +overlay) (lookup +dictionary +offline +docsets) (lsp +peek) (magit +forge) pdf :os (tty +osc) macos :lang emacs-lisp (ess +lsp) (latex +latexmk +cdlatex +fold +lsp) (markdown +grip) (org +pomodoro +dragndrop +jupyter +present +noter +pandoc +pretty +roam2) (python +lsp) sh (yaml +lsp) :email (mu4e +org +gmail) :app calendar everywhere :config literate (default +bindings +smartparens)
packages     (nano-theme) (nano-agenda) (mu4e-alert :disable t) (outline-minor-faces) (bicycle) (google-translate) (plantuml-mode) (graphviz-dot-mode) (org-super-agenda) (org-ql) (org-pomodoro-third-time :recipe (:host github :repo telotortium/org-pomodoro-third-time)) (org-alert) (org-fragtog) (laas) (real-auto-save) (git-auto-commit-mode) (org-roam-ui) (citar) (helm-bibtex) (org-ref) (org-transclusion) (zetteldesk :recipe (:host github :repo Vidianos-Giannitsis/zetteldesk.el)) (pretty-hydra) (oxr :recipe (:host github :repo bdarcus/oxr)) (ess-view-data) (move-dup) (academic-phrases) (company-tabnine) (company-posframe) (consult-yasnippet) (company-wordfreq) (el-secretario :recipe (:repo https://git.sr.ht/~zetagon/el-secretario :files (*))) (org-gtd) (org-edna) (org-agenda-property) (keypression) (good-scroll) (org-graph-view :recipe (:host github :repo alphapapa/org-graph-view)) (mini-modeline) (minions) (org-inline-pdf) (interaction-log) (ftable) (valign) (org-hyperscheduler :recipe (:host github :repo dmitrym0/org-hyperscheduler :files (*))) (company-statistics) (idle-org-agenda)
unpin        org-roam org-roam-bibtex company org-gcal
```

Web browser
```
Name 	Firefox
Version 	99.0.1
Build ID 	20220411174855
```

**Comment by ifinkelstein** [comment] 2022-05-06 01:14
I'm on a vanilla emacs and hence don't have `doom info`
But here's what I've gathered:
`GNU Emacs 28.0.91 (build 1, aarch64-apple-darwin21.2.0, NS appkit-2113.20 Version 12.1 (Build 21C52))`

**Comment by dmitrym0** [comment] 2022-05-06 22:55
Gentlemen, thanks for your patience. It turns out there was a bug that was Firefox specific. I'm not a JavaScript guru. 

It should be fixed in latest main. In case this is not the actual fix, I also added some debugging output on Emacs side. You should see something like:

```
org-hyperscheduler: connection from the browser
Command=[get-agenda] Data=[nil]
Length of encoded agenda=315720
```

Let me know how it goes.

**Comment by maikol-solis** [comment] 2022-05-07 00:16
It worked! Thanks man!

![image](https://user-images.githubusercontent.com/4078489/167229874-2454c651-22ac-4bab-a547-a28cb174b147.png)

**Comment by ifinkelstein** [comment] 2022-05-07 03:11
Confirming that your latest commit also resolved my issue. Thank you very much for this package!

**Comment by dmitrym0** [comment] 2022-05-07 15:50
Good stuff, thanks!

**Closed by dmitrym0** 2022-05-07 15:50 UTC
Labels: bug

**Comment by brunefig** [comment] 2022-07-14 02:20
I'm getting this issue in qutebrowser. No debug output. Works fine in Firefox, so I think this is browser-specific again.
